services:
  ctf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "ctf"
    ports:
      - "5066:5000"
    volumes:
      - .:/app
      - db_volume:/app/db

volumes:
  db_volume:
  