services:
  ctf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "ctf"
    ports:
      - "5066:5000"
    volumes:
      - db_volume:/app/db
    depends_on:
      admin_scheduler:
        condition: service_healthy

  admin_scheduler:
    build:
      context: .
      dockerfile: .config/Dockerfile
    container_name: "ctf_admin"
    volumes:
      - db_volume:/app/db
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5000"]
      interval: 1s
      retries: 360

volumes:
  db_volume:
  